spring:
  mvc:
#    针对静态资源的访问前缀(浏览器访问和服务器内部访问)
#    WelcomePageHandlerMapping 将默认欢迎页写法和访问前缀固定
    static-path-pattern: /res/**
#    指定dispatcher servlet的处理的请求
#    servlet:
#      path:

  #   指定的静态资源的位置(其实这个就是默认的)
  web:
    resources:
      static-locations: ["classpath:/static/"]
#      add-mappings: false 是否开启静态资源访问

  contentnegotiation:
    favor-parameter: true  #开启请求参数内容协商模式

  thymeleaf:
    prefix: "classpath:templates/"
    suffix: ".html"

#    项目访问根路径 thymeleaf的 @{} 会自动加上
#server:
#  servlet:
#    context-path:
